name: test1
on: push
jobs:
  collectCode:
    runs-on: ubuntu-latest
    steps:
      - name: collect_the_code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
